# Generated by Django 4.2.17 on 2024-12-16 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='Task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to='task.task'),
        ),
    ]
