# Generated by Django 4.2.17 on 2024-12-21 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_application_task_applicants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='Task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='applicants',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Apply',
        ),
    ]
