# Generated by Django 4.2.17 on 2024-12-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_apply_task_applicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
