# Generated by Django 4.2.17 on 2024-12-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_apply_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='disability',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
